In [ ]:
# ── Resolva o exercício aqui ──────────────────────────────────────────────
# Passo 1: carregue o CSV

import pandas as pd 
import re   
from datetime import datetime 

df = pd.read_csv(
    'base_rh.csv',
    sep=';',
    encoding='cp1252',
    decimal=','
)









# Passo 5: exportar para Excel


# Passo 6: cole o output do git log aqui como comentário
# git log:

In [26]:
# Passo 2: diagnóstico 
df.shape # Exibe informações das linhas e colunas (1000 linhas e 10 Colunas)

(1000, 10)

In [27]:
df.tail(2) # Exibe as últimas linhas da tabela

,ID_Funcionario,Nome,Departamento,Cargo,Salario,Data_Admissao,Genero,Idade,Estado_Civil,Status
998,999,Thales Farias,Produção,Analista,9430.62,25/12/2019,M,41,Solteiro,Ativo
999,1000,Sra. Maysa Costela,Produção,Técnico,12549.72,14/11/2022,M,46,Viúvo,Inativo

In [ ]:
df.head() # Exibe as 5 primeiras linhas da tabela

,ID_Funcionario,Nome,Departamento,Cargo,Salario,Data_Admissao,Genero,Idade,Estado_Civil,Status
0,1,Julia Nunes,Logística,Coordenador,9088.34,13/08/2024,F,43,Solteiro,Inativo
1,2,Sr. Gustavo Duarte,TI,Gerente,8155.98,29/04/2017,F,59,Solteiro,Inativo
2,3,Srta. Mariana Cunha,RH,Coordenador,14027.93,11/12/2024,F,27,Divorciado,Ativo
3,4,Ana Sophia da Cruz,Produção,Técnico,6647.97,16/06/2019,M,50,Casado,Inativo
4,5,Dr. Nicolas Pinto,Produção,Gerente,8730.19,29/03/2019,F,62,Casado,Inativo

In [20]:
df.tail() # Exibe as 5 últimas linhas da tabela

,ID_Funcionario,Nome,Departamento,Cargo,Salario,Data_Admissao,Genero,Idade,Estado_Civil,Status
995,996,Matheus Aragão,Financeiro,Analista,11389.03,06/05/2022,F,26,Viúvo,Ativo
996,997,Ryan Martins,Financeiro,Analista,14060.42,05/06/2023,F,37,Viúvo,Ativo
997,998,Isabelly Ferreira,TI,Gerente,2348.73,29/12/2023,F,58,Solteiro,Inativo
998,999,Thales Farias,Produção,Analista,9430.62,25/12/2019,M,41,Solteiro,Ativo
999,1000,Sra. Maysa Costela,Produção,Técnico,12549.72,14/11/2022,M,46,Viúvo,Inativo

In [21]:
df.info() # Exibe informações do DataFrame, como tipos de dados e valores

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID_Funcionario  1000 non-null   int64
 1   Nome            1000 non-null   str
 2   Departamento    1000 non-null   str
 3   Cargo           1000 non-null   str
 4   Salario         1000 non-null   float64
 5   Data_Admissao   1000 non-null   str
 6   Genero          1000 non-null   str
 7   Idade           1000 non-null   int64
 8   Estado_Civil    1000 non-null   str
 9   Status          1000 non-null   str
dtypes: float64(1), int64(2), str(7)
memory usage: 78.3 KB

In [23]:
df.describe() # Exibe estastísticas descritivas para as colunas numéricas do DataFrame

       ID_Funcionario       Salario        Idade
count     1000.000000   1000.000000  1000.000000
mean       500.500000   8579.951780    41.399000
std        288.819436   3657.365307    13.665817
min          1.000000   2000.710000    18.000000
25%        250.750000   5564.545000    30.000000
50%        500.500000   8571.135000    41.000000
75%        750.250000  11554.630000    53.000000
max       1000.000000  14954.510000    65.000000

In [33]:
df['Cargo'].value_counts() # Exibe a contagem de valores únicos na coluna escolhida que está entre aspas ' '

Cargo
Coordenador    225
Gerente        221
Assistente     199
Analista       178
Técnico        177
Name: count, dtype: int64

In [34]:
df.isnull().sum() # Exibe a contagem de valores nulos em cada coluna do DataFrame

ID_Funcionario    0
Nome              0
Departamento      0
Cargo             0
Salario           0
Data_Admissao     0
Genero            0
Idade             0
Estado_Civil      0
Status            0
dtype: int64

In [42]:
# Passo 3: converter datas e criar colunas derivadas 
df['Data_Admissao'] = pd.to_datetime(df['Data_Admissao'], format='%d/%m/%Y', errors='coerce')
df["Ano"] = df["Data_Admissao"].dt.year
df["Mês"] = df["Data_Admissao"].dt.month
df["trim"] = df["Data_Admissao"].dt.quarter
df["Tempo"] = ((pd.Timestamp.today() - df["Data_Admissao"]).dt.days / 365.25).round(1)

In [43]:
df.head()

,ID_Funcionario,Nome,Departamento,Cargo,Salario,Data_Admissao,Genero,Idade,Estado_Civil,Status,Ano,Mês,trim,Tempo
0,1,Julia Nunes,Logística,Coordenador,9088.34,2024-08-13,F,43,Solteiro,Inativo,2024,8,3,1.7
1,2,Sr. Gustavo Duarte,TI,Gerente,8155.98,2017-04-29,F,59,Solteiro,Inativo,2017,4,2,9.0
2,3,Srta. Mariana Cunha,RH,Coordenador,14027.93,2024-12-11,F,27,Divorciado,Ativo,2024,12,4,1.4
3,4,Ana Sophia da Cruz,Produção,Técnico,6647.97,2019-06-16,M,50,Casado,Inativo,2019,6,2,6.9
4,5,Dr. Nicolas Pinto,Produção,Gerente,8730.19,2019-03-29,F,62,Casado,Inativo,2019,3,1,7.1

In [45]:
# Passo 4: groupby — maior e menor média de tempo de casa 

df.groupby('Departamento')['Salario'].mean().round(2)   
df.groupby('Departamento')['Salario'].size().sort_values(ascending=False)

Departamento
Financeiro    189
Produção      182
RH            166
Vendas        160
Logística     156
TI            147
Name: Salario, dtype: int64